project_id = "yhlnmrhtiixzdovqxdei"

[functions.process-payment]
verify_jwt = false

[functions.faspay-notify]
enabled = true
verify_jwt = true
import_map = "./functions/faspay-notify/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/faspay-notify/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/faspay-notify/*.html" ]
